name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 在 main 分支有更新（包括回滚）时触发
  workflow_dispatch:  # 手动触发，用于测试或调试

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log Step Execution
        run: echo "Step [Build] executed for commit ${{ github.sha }}"

  test:
    runs-on: ubuntu-latest
    needs: build  # 确保测试在构建完成后运行

    steps:
      - name: Log Step Execution
        run: echo "Step [Test] executed for commit ${{ github.sha }}"

  deploy:
    runs-on: ubuntu-latest
    needs: test  # 确保部署在测试完成后运行

    steps:
      - name: Log Step Execution
        run: echo "Step [Deploy] executed for commit ${{ github.sha }}"
